version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dev-stack-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: default_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - dev-stack-network
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: dev-stack-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - dev-stack-network

  memcached:
    image: memcached:1.6-alpine
    container_name: dev-stack-memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    command: memcached -m 256
    networks:
      - dev-stack-network

  redis:
    image: redis:7-alpine
    container_name: dev-stack-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev-stack-network
    command: redis-server --appendonly yes

volumes:
  mysql_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local

networks:
  dev-stack-network:
    driver: bridge
